name: Export dataset
on:
  schedule:
    # runs every day at 1am EDT
    - cron: '0 10 * * *'

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Export dataset
        uses: sanity-io/github-action-sanity@v0.2-alpha
        env:
          SANITY_AUTH_TOKEN: ${{ secrets.SANITY_AUTH_TOKEN }}
        with:
          args: dataset export production backups/backup.tar.gz
      - uses: actions/upload-artifact@v2
        with:
          name: backup
          path: backups/backup.tar.gz
