name: Backup Routine
on:
  push:
    branches: main
  schedule:
    # Runs at 04:00 UTC on the 1st and 17th of every month
    - cron: '0 8 * * *'

jobs:
  backup-dataset:
    runs-on: ubuntu-22.04
    name: Backup dataset
    steps:
      # build project
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Install dependencies
        run: yarn install
      - name: Backup dataset
        run: npx sanity dataset export production backups/production.tar.gz
        env:
          SANITY_AUTH_TOKEN: ${{ secrets.SANITY_AUTH_TOKEN }}
      - name: Upload backup.tar.gz
        uses: actions/upload-artifact@v2
        with:
          name: backup-tarball
          path: backups/backup.tar.gz
          # Fails the workflow if no files are found; defaults to 'warn'
          if-no-files-found: error
